spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 130511198727-sl1r5ue0ntnef26kb7jjrqucl0ro0nt9.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
          github:
            client-id: Iv23liq9bcQ0BMGkxZf0
            client-secret: 7904de8c92adcafa398ace967e40838d54cc734e
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: GitHub
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id